name: Open URL Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute
  workflow_dispatch:  # Allows manual start

jobs:
  open_url:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request
        run: |
          curl -X GET "https://cdn.qw03.xyz/h/910001002.html?code=31WC3Q&uid=130159769"
