name: Open URL Every Minute (Debug Mode)

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 1 minute
  workflow_dispatch:  # Allow manual start

jobs:
  open_url:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request and Show Response
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" "https://cdn.qw03.xyz/h/910001002.html?code=31WC3Q&uid=130159769")
          echo "HTTP Status Code: $response"
          echo "Response Body:"
          cat response.txt
